functionsDirectory = "C:\\Users\\abhay\\OneDrive\\Desktop\\Degree Defenders\\frontend\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\abhay\\OneDrive\\Desktop\\Degree Defenders\\frontend\\netlify deploy --prod --dir=build"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\abhay\\OneDrive\\Desktop\\Degree Defenders\\frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]